[build]
  functions = "netlify/functions"
  publish = "."

[functions."send-reminders"]
  schedule = "@daily"

[functions."fetch-google-reviews"]
  schedule = "@daily"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
